#!/bin/bash
set -e

SONATYPE_WORK=`dirname $NEXUS_HOME`/sonatype-work
if [[ ! -d $SONATYPE_WORK || `stat -c %U $SONATYPE_WORK` != 'nexus' ]]; then
    mkdir -p $SONATYPE_WORK
    chown -R nexus:nexus $SONATYPE_WORK
fi

su -l -c "$NEXUS_HOME/bin/nexus start" nexus
tail -F $SONATYPE_WORK/nexus/logs/nexus.log
