#!/bin/bash
set -e

POSTGRESQL_VERSION=${POSTGRES_VERSION:-"9.3"}

POSTGRESQL_USER=${POSTGRESQL_USER:-"docker"}
POSTGRESQL_PASS=${POSTGRESQL_PASS:-"docker"}
POSTGRESQL_DB=${POSTGRESQL_DB:-"docker"}
POSTGRESQL_TEMPLATE=${POSTGRESQL_TEMPLATE:-"DEFAULT"}

POSTGRESQL_BIN=/usr/lib/postgresql/$POSTGRESQL_VERSION/bin/postgres
POSTGRESQL_CONFIG_FILE=/etc/postgresql/$POSTGRESQL_VERSION/main/postgresql.conf
POSTGRESQL_DATA=/var/lib/postgresql/$POSTGRESQL_VERSION/main

POSTGRESQL_SINGLE="sudo -u postgres $POSTGRESQL_BIN --single --config-file=$POSTGRESQL_CONFIG_FILE"

if [ ! -d $POSTGRESQL_DATA ]; then
    mkdir -p $POSTGRESQL_DATA
    chown -R postgres:postgres $POSTGRESQL_DATA
    sudo -u postgres /usr/lib/postgresql/$POSTGRESQL_VERSION/bin/initdb -D $POSTGRESQL_DATA -E 'UTF-8' --lc-collate='en_US.UTF-8' --lc-ctype='en_US.UTF-8'
    ln -s /etc/ssl/certs/ssl-cert-snakeoil.pem $POSTGRESQL_DATA/server.crt
    ln -s /etc/ssl/private/ssl-cert-snakeoil.key $POSTGRESQL_DATA/server.key
fi

if [ ! -d /var/lib/postgresql ]; then
    mkdir -P /var/lib/postgresql
    chown -R postgres:postgres /var/lib/postgresql
fi

if [[ -z $($POSTGRESQL_SINGLE <<< 'SELECT usename FROM pg_catalog.pg_user;' | grep "usename = \"$POSTGRESQL_USER\"") ]]; then
    $POSTGRESQL_SINGLE <<< "CREATE USER $POSTGRESQL_USER WITH SUPERUSER;" > /dev/null
    $POSTGRESQL_SINGLE <<< "ALTER USER $POSTGRESQL_USER WITH PASSWORD '$POSTGRESQL_PASS';" > /dev/null
fi

if [[ -z $($POSTGRESQL_SINGLE <<< 'SELECT datname FROM pg_catalog.pg_database;' | grep "datname = \"$POSTGRESQL_DB\"") ]]; then
    $POSTGRESQL_SINGLE <<< "CREATE DATABASE $POSTGRESQL_DB OWNER $POSTGRESQL_USER TEMPLATE $POSTGRESQL_TEMPLATE;" > /dev/null
fi

exec sudo -u postgres $POSTGRESQL_BIN --config-file=$POSTGRESQL_CONFIG_FILE
